version: '1.0.0'

services:

  wendy_backend:
    container_name: wendy_backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/home/app/backend
    links:
      - wendy_db


  wendy_db:
    container_name: wendy_db
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - wendy:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    attach: false
  
volumes:
  wendy:
