version: '1'

services:

  wendy_backend:
    container_name: wendy_backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./:/home/app/backend


  wendydb:
    container_name: wendydb
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - wendy:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    attach: false
volumes:
  wendy:
